apiVersion: security.policy.gloo.solo.io/v2
kind: WAFPolicy
metadata:
  name: httpbin-user-agent-waf
  namespace: httpbin
spec:
  applyToRoutes:
  - route:
      labels:
        waf: "true"
  config:
    customInterventionMessage: Missing User-Agent header
    customRuleSets:
    - ruleStr: |
        SecRuleEngine On
        SecRule &REQUEST_HEADERS:User-Agent "@eq 0" "deny,status:404,id:107,phase:1,msg:'Path not found'"
    disableCoreRuleSet: true