# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of resources to be Applied
resources:
- collaboration-workspace.yaml
- collaboration-workspacesettings.yaml
- drawio-rt-443.yaml
- drawio.yaml
- etherdraw-rt-443.yaml
- etherdraw.yaml
- etherpad-rt-443.yaml
- etherpad.yaml
- ghost-blog-extauth-policy-443.yaml
- ghost-admin-delegate-rt.yaml
- ghost-main-delegate-rt.yaml
- ghost-root-rt.yaml
- ghost-blog.yaml
- ghost-ratelimit-transformationfilter.yaml
- ghost-ratelimitclientconfig.yaml
- ghost-ratelimitpolicy.yaml
- ghost-ratelimitserverconfig.yaml
- ghost-ratelimitserversettings.yaml
- plants-blog-rt-443.yaml
- plants-blog.yaml

