apiVersion: admin.gloo.solo.io/v2
kind: Workspace
metadata:
  name: podinfo
  namespace: gloo-mesh
spec:
  workloadClusters:
  - name: 'mgmt'
    namespaces:
    - name: podinfo-config
  - name: '*'
    namespaces:
    - name: podinfo