apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  labels:
    expose: "true"
  name: homer-web-portal-rt-80
  namespace: web-portal
spec:
  hosts:
  - 'homer.glootest.com'
  - 'homer-local.glootest.com'
  http:
  - forwardTo:
      destinations:
      - port:
          number: 8080
        ref:
          cluster: mgmt
          name: homer-portal
          namespace: web-portal
    name: homer
  virtualGateways:
  - cluster: mgmt
    name: mgmt-north-south-gw-80
    namespace: istio-gateways
  workloadSelectors: []