apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: games-workspacesettings
  namespace: supermario
spec:
  exportTo:
  - resources:
    - kind: ALL
      labels:
        expose: "true"
    workspaces:
    - name: gateways
  importFrom:
  - resources:
    - kind: SERVICE
    workspaces:
    - name: gateways
  options:
    federation:
      enabled: false
      hostSuffix: global