apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: supermario-rt-443
  namespace: supermario
  labels:
    expose: "true"
spec:
  hosts:
    - 'supermario.kapoozi.com'
  virtualGateways:
    - name: mgmt-north-south-gw-443
      namespace: istio-gateways
      cluster: mgmt
  workloadSelectors: []
  http:
    - name: supermario
      matchers:
      - uri:
          prefix: /
      forwardTo:
        destinations:
        - ref:
            name: supermario
            namespace: supermario
          port:
            number: 8080