apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bombardier-plantsblog
  namespace: argocd
spec:
  destination:
    namespace: collaboration-tools
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/solo-io/gitops-library'
    path: bombardier-loadgen/helm
    targetRevision: HEAD
    helm:
      parameters:
      - name: url
        value: 'https://plants.kapoozi.com'
      - name: name_suffix
        value: 'plantsblog'
      - name: namespace
        value: 'collaboration-tools'
      - name: loops
        value: '10000'
      - name: connections
        value: '5'
      - name: duration_seconds
        value: '60s'
      - name: rate
        value: '4'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true