apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: plex-rt-443
  namespace: plex-config
spec:
  hosts:
    - 'watch.kapoozi.com'
  virtualGateways:
    - name: cluster1-north-south-gw-443
      namespace: istio-gateways
      cluster: mgmt
  workloadSelectors: []
  http:
    - name: plex-server
      matchers:
      - uri:
          prefix: /
      forwardTo:
        destinations:
          - ref:
              name: plex-vd
              namespace: plex-config
            kind: VIRTUAL_DESTINATION
            port:
              number: 32400