apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: numaflow-rt-443
  namespace: numaflow-config
spec:
  hosts:
    - 'numaflow.kapoozi.com'
  virtualGateways:
    - name: mgmt-north-south-gw-443
      namespace: istio-gateways
      cluster: mgmt
  workloadSelectors: []
  http:
    - name: numaflow
      matchers:
      - uri:
          prefix: /
      forwardTo:
        destinations:
        - ref:
            name: numaflow
            namespace: numaflow
          port:
            number: 8443