apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  labels:
    expose: "true"
  name: cluster1-argo-rt-443
  namespace: argocd
spec:
  hosts:
  - 'argocd-cluster1.kapoozi.com'
  http:
  - name: argocd
    labels:
      waf: "true"
      #argocd-oauth: "true"
    matchers:
    - uri:
        prefix: /argo
    forwardTo:
      destinations:
      - port:
          number: 443
        ref:
          cluster: cluster1
          name: argocd-server
          namespace: argocd
    matchers:
      - uri:
          prefix: /
      - uri:
          prefix: /callback
  virtualGateways:
  - cluster: mgmt
    name: cluster1-north-south-gw-443
    namespace: istio-gateways
  workloadSelectors: []