apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  labels:
    expose: "true"
  name: cluster2-argo-rt-443
  namespace: argocd
spec:
  hosts:
  - 'argocd-cluster2.kapoozi.com'
  http:
  - name: argocd
    labels:
      waf: "true"
      #argocd-oauth: "true"
    matchers:
      - uri:
          prefix: /argo
      - uri:
          prefix: /callback
    forwardTo:
      destinations:
      - port:
          number: 443
        ref:
          cluster: cluster2
          name: argocd-server
          namespace: argocd
  virtualGateways:
  - cluster: mgmt
    name: cluster2-north-south-gw-443
    namespace: istio-gateways
  workloadSelectors: []