apiVersion: admin.gloo.solo.io/v2
kind: Workspace
metadata:
  name: ops-team
  namespace: gloo-mesh
spec:
  workloadClusters:
  - name: mgmt
    namespaces:
    - name: gloo-mesh
    - name: istio-system
    - name: web-portal
    - name: ops-team-config
  - name: cluster1
    namespaces:
    - name: uptime
  - name: '*'
    namespaces:
    - name: argocd
    - name: istio-gateways
    - name: gloo-mesh-addons
    - name: prometheus
    - name: longhorn-system