apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  labels:
    expose: "true"
  name: grafana-ui-443
  namespace: gloo-mesh
spec:
  hosts:
  - 'grafana.kapoozi.com'
  http:
  - name: grafana-ui
    labels:
      waf: "true"
      oauth: "true"
    matchers:
      - uri:
          prefix: /grafana
      - uri:
          prefix: /callback
    forwardTo:
      destinations:
      - port:
          number: 3000
        ref:
          cluster: mgmt
          name: grafana
          namespace: istio-system
  - name: grafana-ui-cluster1
    labels:
      waf: "true"
      #oauth: "true"
    matchers:
      - uri:
          prefix: /cluster1
      - uri:
          prefix: /callback
    forwardTo:
      destinations:
      - port:
          number: 80
        ref:
          cluster: cluster1
          name: prometheus-helm-grafana
          namespace: prometheus
  virtualGateways:
  - cluster: mgmt
    name: mgmt-north-south-gw-443
    namespace: istio-gateways
  workloadSelectors: []