apiVersion: security.policy.gloo.solo.io/v2
kind: ExtAuthPolicy
metadata:
  name: longhorn
  namespace: ops-team-config
spec:
  applyToRoutes:
  - route:
      labels:
        route_name: longhorn-ui-mgmt
  config:
    server:
      name: mgmt-ext-auth-server
      namespace: gloo-mesh
      cluster: mgmt
    glooAuth:
      configs:
      - oauth2:
          oidcAuthorizationCode:
            appUrl: https://storage.kapoozi.com
            callbackPath: /callback
            clientId: 0oa5zlc69fbDNh2Hf5d7
            clientSecretRef:
              name: ops-team-okta-client-secret
              namespace: ops-team-config
            issuerUrl: https://dev-22653158.okta.com/oauth2/default
            session:
              failOnFetchFailure: false
              redis:
                cookieName: longhorn-okta-session
                options:
                  host: redis.gloo-mesh-addons:6379
                allowRefreshing: false
              cookieOptions:
                maxAge: "1800"
            scopes:
            - email
            logoutPath: /logout
            #afterLogoutUrl: /get
            headers:
              idTokenHeader: Jwt
              #idTokenHeader: x-id-token
              #accessTokenHeader: x-access-token