# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of resources to be Applied
resources:
- ../../base/active/
- productpage-accesspolicy.yaml
- plow-loadgen-argo.yaml

patchesStrategicMerge:
- patches/bookinfo-oauth-rt-443.yaml