apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-ca
  namespace: gloo-mesh
spec:
  isCA: true
  duration: 8760h0m0s # 1y
  #secretName: istio-ca
  secretName: dummy-signing-cert
  commonName: istio-ca
  subject:
    organizations:
    - cluster.local
    - istio
    - cert-manager
  issuerRef:
    name: selfsigned
    kind: Issuer
    group: cert-manager.io