apiVersion: networking.gloo.solo.io/v2
kind: VirtualDestination
metadata:
  name: podinfo-vd
  namespace: podinfo-config
spec:
  hosts:
  - podinfo-vd.mesh
  services:
  - labels:
      app.kubernetes.io/name: podinfo
  ports:
  - number: 9898
    protocol: HTTP
    targetPort:
      name: http
