apiVersion: admin.gloo.solo.io/v2
kind: Workspace
metadata:
  name: numaflow
  namespace: gloo-mesh
spec:
  workloadClusters:
  - name: 'mgmt'
    namespaces:
    - name: numaflow-config
  - name: '*'
    namespaces:
    - name: numaflow-system
    - name: numaflow