apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  labels:
    expose: "true"
  name: productpage-rt-443
  namespace: bookinfo-frontends
spec:
  hosts:
  - 'bookinfo.kapoozi.com'
  http:
  - name: productpage
    labels:
      waf: "true"
      oauth: "true"
      ratelimited: "true"
    matchers:
    - uri:
        exact: /productpage
    - uri:
        prefix: /static
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /callback
    forwardTo:
      destinations:
      - port:
          number: 9080
        ref:
          name: productpage
          namespace: bookinfo-frontends
          cluster: cluster1
  - name: api-v1
    labels:
      waf: "true"
      ratelimited: "true"
    matchers:
    - uri:
        exact: /api/v1/products
    forwardTo:
      destinations:
      - port:
          number: 9080
        ref:
          name: productpage
          namespace: bookinfo-frontends
  - name: api-v1-product1
    labels:
      waf: "true"
      ratelimited: "true"
    matchers:
    - uri:
        exact: /api/v1/products/1
      headers:
        - name: end-user
          value: jason
    forwardTo:
      destinations:
      - port:
          number: 9080
        ref:
          name: productpage
          namespace: bookinfo-frontends
  - name: plow-productpage-rewrite
    labels:
      waf: "true"
      ratelimited: "true"
    matchers:
    - uri:
        prefix: /plow
    forwardTo:
      pathRewrite: /
      destinations:
      - ref:
          name: plow-productpage
          namespace: bookinfo-frontends
        port:
          number: 18888
  - name: plow-productpage
    labels:
      waf: "true"
      ratelimited: "true"
    matchers:
    - uri:
        prefix: /data
    - uri:
        prefix: /echarts
    forwardTo:
      destinations:
      - ref:
          name: plow-productpage
          namespace: bookinfo-frontends
        port:
          number: 18888
  virtualGateways:
  - cluster: mgmt
    name: mgmt-north-south-gw-443
    namespace: istio-gateways
  workloadSelectors: []