apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-content
  namespace: collaboration-tools
  labels:
    app: blog
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: civo-volume