apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  labels:
    expose: "true"
  name: productpage-rt-443
  namespace: bookinfo-frontends
spec:
  hosts:
  - 'bookinfo.kapoozi.com'
  http:
  - forwardTo:
      destinations:
      - port:
          number: 9080
        ref:
          name: productpage
          namespace: bookinfo-frontends
    labels:
      waf: "true"
      oauth: "true"
      ratelimited: "true"
    matchers:
    - uri:
        exact: /productpage
    - uri:
        prefix: /static
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /callback
    name: productpage
  - forwardTo:
      destinations:
      - port:
          number: 9080
        ref:
          name: productpage
          namespace: bookinfo-frontends
    labels:
      waf: "true"
      ratelimited: "true"
    matchers:
    - uri:
        prefix: /api/v1/products
    name: api-v1
  virtualGateways:
  - cluster: mgmt
    name: mgmt-north-south-gw-443
    namespace: istio-gateways
  workloadSelectors: []