apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: bank-demo-rt-443
  namespace: bank-demo
  labels:
    expose: "true"
spec:
  hosts:
    - 'bank.kapoozi.com'
  virtualGateways:
    - name: mgmt-north-south-gw-443
      namespace: istio-gateways
      cluster: mgmt
  workloadSelectors: []
  http:
    - name: bank-demo
      matchers:
      - uri:
          prefix: /
      - uri:
          prefix: /home
      forwardTo:
        destinations:
        - ref:
            name: frontend
            namespace: bank-demo
          port:
            number: 80
      labels:
        waf: "true"