apiVersion: v1
kind: Secret
metadata:
  name:  ghost-okta-client-secret
  namespace: collaboration-tools
type: extauth.solo.io/oauth
data:
  client-secret: Uzk0Uld5VlktTGZnejdkd0hwSGNjazhWQmN6YjVjSk83MVdYemRGOQ==