apiVersion: security.policy.gloo.solo.io/v2
kind: AccessPolicy
metadata:
  clusterName: mgmt
  name: ns-access-productpage
  namespace: bookinfo-frontends
  annotations:
    clusterName: mgmt
spec:
  applyToDestinations:
  - selector:
      name: productpage
      namespace: bookinfo-frontends
      cluster: mgmt
      workspace: bookinfo
  config:
    authn:
      tlsMode: STRICT
    authz:
      allowedClients:
      - serviceAccountSelector:
          name: istio-ingressgateway
          namespace: istio-gateways
          cluster: mgmt
      allowedPaths:
      - /productpage*
      allowedMethods:
      - GET
      - POST