apiVersion: security.policy.gloo.solo.io/v2
kind: AccessPolicy
metadata:
  name: productpage-accesspolicy
  namespace: bookinfo-frontends
spec:
  applyToDestinations:
  - selector:
      name: productpage
      namespace: bookinfo-frontends
      cluster: mgmt
      workspace: bookinfo
  config:
    authn:
      tlsMode: STRICT
    authz:
      allowedClients:
      - serviceAccountSelector:
          name: istio-ingressgateway
          namespace: istio-gateways
          cluster: mgmt
      allowedPaths:
      - /productpage*
      - /api/v1/products
      allowedMethods:
      - GET
      - POST